apiVersion: v1
kind: Service
metadata:
  name: mkdocs-gke-service
  namespace: mkdocs
  labels:
    app: mkdocs-webapp
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: mkdocs-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
